export const COUNTRIES_DATA = [
    { "name": "Afghanistan", "currency": "Afghan Afghani", "code": "AFN", "symbol": "؋", "tax": { "type": "BRT", "rate": 10 } },
    { "name": "Albania", "currency": "Albanian Lek", "code": "ALL", "symbol": "L", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Algeria", "currency": "Algerian Dinar", "code": "DZD", "symbol": "د.ج", "tax": { "type": "VAT", "rate": 19 } },
    { "name": "Andorra", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "IGI", "rate": 4.5 } },
    { "name": "Angola", "currency": "Angolan Kwanza", "code": "AOA", "symbol": "Kz", "tax": { "type": "VAT", "rate": 14 } },
    { "name": "Antigua and Barbuda", "currency": "East Caribbean Dollar", "code": "XCD", "symbol": "$", "tax": { "type": "ABST", "rate": 15 } },
    { "name": "Argentina", "currency": "Argentine Peso", "code": "ARS", "symbol": "$", "tax": { "type": "VAT", "rate": 21 } },
    { "name": "Armenia", "currency": "Armenian Dram", "code": "AMD", "symbol": "֏", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Australia", "currency": "Australian Dollar", "code": "AUD", "symbol": "$", "tax": { "type": "GST", "rate": 10 } },
    { "name": "Austria", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Azerbaijan", "currency": "Azerbaijani Manat", "code": "AZN", "symbol": "₼", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Bahamas", "currency": "Bahamian Dollar", "code": "BSD", "symbol": "$", "tax": { "type": "VAT", "rate": 12 } },
    { "name": "Bahrain", "currency": "Bahraini Dinar", "code": "BHD", "symbol": ".د.ب", "tax": { "type": "VAT", "rate": 10 } },
    { "name": "Bangladesh", "currency": "Bangladeshi Taka", "code": "BDT", "symbol": "৳", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Barbados", "currency": "Barbadian Dollar", "code": "BBD", "symbol": "$", "tax": { "type": "VAT", "rate": 17.5 } },
    { "name": "Belarus", "currency": "Belarusian Ruble", "code": "BYN", "symbol": "Br", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Belgium", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 21 } },
    { "name": "Belize", "currency": "Belize Dollar", "code": "BZD", "symbol": "$", "tax": { "type": "GST", "rate": 12.5 } },
    { "name": "Benin", "currency": "West African CFA Franc", "code": "XOF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Bhutan", "currency": "Bhutanese Ngultrum", "code": "BTN", "symbol": "Nu.", "tax": { "type": "GST", "rate": 7 } },
    { "name": "Bolivia", "currency": "Bolivian Boliviano", "code": "BOB", "symbol": "Bs.", "tax": { "type": "VAT", "rate": 13 } },
    { "name": "Bosnia and Herzegovina", "currency": "Bosnia and Herzegovina Convertible Mark", "code": "BAM", "symbol": "KM", "tax": { "type": "VAT", "rate": 17 } },
    { "name": "Botswana", "currency": "Botswana Pula", "code": "BWP", "symbol": "P", "tax": { "type": "VAT", "rate": 14 } },
    { "name": "Brazil", "currency": "Brazilian Real", "code": "BRL", "symbol": "R$", "tax": { "type": "ICMS", "rate": 17 } },
    { "name": "Brunei", "currency": "Brunei Dollar", "code": "BND", "symbol": "$", "tax": { "type": "None", "rate": 0 } },
    { "name": "Bulgaria", "currency": "Bulgarian Lev", "code": "BGN", "symbol": "лв", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Burkina Faso", "currency": "West African CFA Franc", "code": "XOF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Burundi", "currency": "Burundian Franc", "code": "BIF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Cabo Verde", "currency": "Cape Verdean Escudo", "code": "CVE", "symbol": "$", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Cambodia", "currency": "Cambodian Riel", "code": "KHR", "symbol": "៛", "tax": { "type": "VAT", "rate": 10 } },
    { "name": "Cameroon", "currency": "Central African CFA Franc", "code": "XAF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 19.25 } },
    { "name": "Canada", "currency": "Canadian Dollar", "code": "CAD", "symbol": "$", "tax": { "type": "GST", "rate": 5 } },
    { "name": "Central African Republic", "currency": "Central African CFA Franc", "code": "XAF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 19 } },
    { "name": "Chad", "currency": "Central African CFA Franc", "code": "XAF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Chile", "currency": "Chilean Peso", "code": "CLP", "symbol": "$", "tax": { "type": "VAT", "rate": 19 } },
    { "name": "China", "currency": "Chinese Yuan", "code": "CNY", "symbol": "¥", "tax": { "type": "VAT", "rate": 13 } },
    { "name": "Colombia", "currency": "Colombian Peso", "code": "COP", "symbol": "$", "tax": { "type": "VAT", "rate": 19 } },
    { "name": "Comoros", "currency": "Comorian Franc", "code": "KMF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 10 } },
    { "name": "Congo, Democratic Republic of the", "currency": "Congolese Franc", "code": "CDF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 16 } },
    { "name": "Congo, Republic of the", "currency": "Central African CFA Franc", "code": "XAF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Costa Rica", "currency": "Costa Rican Colón", "code": "CRC", "symbol": "₡", "tax": { "type": "VAT", "rate": 13 } },
    { "name": "Croatia", "currency": "Croatian Kuna", "code": "HRK", "symbol": "kn", "tax": { "type": "VAT", "rate": 25 } },
    { "name": "Cuba", "currency": "Cuban Peso", "code": "CUP", "symbol": "$", "tax": { "type": "Sales", "rate": 20 } },
    { "name": "Cyprus", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 19 } },
    { "name": "Czech Republic", "currency": "Czech Koruna", "code": "CZK", "symbol": "Kč", "tax": { "type": "VAT", "rate": 21 } },
    { "name": "Denmark", "currency": "Danish Krone", "code": "DKK", "symbol": "kr", "tax": { "type": "VAT", "rate": 25 } },
    { "name": "Djibouti", "currency": "Djiboutian Franc", "code": "DJF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 10 } },
    { "name": "Dominica", "currency": "East Caribbean Dollar", "code": "XCD", "symbol": "$", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Dominican Republic", "currency": "Dominican Peso", "code": "DOP", "symbol": "$", "tax": { "type": "ITBIS", "rate": 18 } },
    { "name": "East Timor", "currency": "United States Dollar", "code": "USD", "symbol": "$", "tax": { "type": "Sales", "rate": 2.5 } },
    { "name": "Ecuador", "currency": "United States Dollar", "code": "USD", "symbol": "$", "tax": { "type": "VAT", "rate": 12 } },
    { "name": "Egypt", "currency": "Egyptian Pound", "code": "EGP", "symbol": "£", "tax": { "type": "VAT", "rate": 14 } },
    { "name": "El Salvador", "currency": "United States Dollar", "code": "USD", "symbol": "$", "tax": { "type": "VAT", "rate": 13 } },
    { "name": "Equatorial Guinea", "currency": "Central African CFA Franc", "code": "XAF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Eritrea", "currency": "Eritrean Nakfa", "code": "ERN", "symbol": "Nkf", "tax": { "type": "Sales", "rate": 5 } },
    { "name": "Estonia", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Eswatini", "currency": "Swazi Lilangeni", "code": "SZL", "symbol": "L", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Ethiopia", "currency": "Ethiopian Birr", "code": "ETB", "symbol": "Br", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Fiji", "currency": "Fijian Dollar", "code": "FJD", "symbol": "$", "tax": { "type": "VAT", "rate": 9 } },
    { "name": "Finland", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 24 } },
    { "name": "France", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Gabon", "currency": "Central African CFA Franc", "code": "XAF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Gambia", "currency": "Gambian Dalasi", "code": "GMD", "symbol": "D", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Georgia", "currency": "Georgian Lari", "code": "GEL", "symbol": "₾", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Germany", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 19 } },
    { "name": "Ghana", "currency": "Ghanaian Cedi", "code": "GHS", "symbol": "₵", "tax": { "type": "VAT", "rate": 12.5 } },
    { "name": "Greece", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 24 } },
    { "name": "Grenada", "currency": "East Caribbean Dollar", "code": "XCD", "symbol": "$", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Guatemala", "currency": "Guatemalan Quetzal", "code": "GTQ", "symbol": "Q", "tax": { "type": "VAT", "rate": 12 } },
    { "name": "Guinea", "currency": "Guinean Franc", "code": "GNF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Guinea-Bissau", "currency": "West African CFA Franc", "code": "XOF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Guyana", "currency": "Guyanese Dollar", "code": "GYD", "symbol": "$", "tax": { "type": "VAT", "rate": 14 } },
    { "name": "Haiti", "currency": "Haitian Gourde", "code": "HTG", "symbol": "G", "tax": { "type": "VAT", "rate": 10 } },
    { "name": "Honduras", "currency": "Honduran Lempira", "code": "HNL", "symbol": "L", "tax": { "type": "Sales", "rate": 15 } },
    { "name": "Hungary", "currency": "Hungarian Forint", "code": "HUF", "symbol": "Ft", "tax": { "type": "VAT", "rate": 27 } },
    { "name": "Iceland", "currency": "Icelandic Króna", "code": "ISK", "symbol": "kr", "tax": { "type": "VAT", "rate": 24 } },
    { "name": "India", "currency": "Indian Rupee", "code": "INR", "symbol": "₹", "tax": { "type": "GST", "rate": 18 } },
    { "name": "Indonesia", "currency": "Indonesian Rupiah", "code": "IDR", "symbol": "Rp", "tax": { "type": "VAT", "rate": 11 } },
    { "name": "Iran", "currency": "Iranian Rial", "code": "IRR", "symbol": "﷼", "tax": { "type": "VAT", "rate": 9 } },
    { "name": "Iraq", "currency": "Iraqi Dinar", "code": "IQD", "symbol": "ع.د", "tax": { "type": "Sales", "rate": 5 } },
    { "name": "Ireland", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 23 } },
    { "name": "Israel", "currency": "Israeli New Shekel", "code": "ILS", "symbol": "₪", "tax": { "type": "VAT", "rate": 17 } },
    { "name": "Italy", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 22 } },
    { "name": "Jamaica", "currency": "Jamaican Dollar", "code": "JMD", "symbol": "J$", "tax": { "type": "GCT", "rate": 15 } },
    { "name": "Japan", "currency": "Japanese Yen", "code": "JPY", "symbol": "¥", "tax": { "type": "Consumption", "rate": 10 } },
    { "name": "Jordan", "currency": "Jordanian Dinar", "code": "JOD", "symbol": "د.ا", "tax": { "type": "GST", "rate": 16 } },
    { "name": "Kazakhstan", "currency": "Kazakhstani Tenge", "code": "KZT", "symbol": "₸", "tax": { "type": "VAT", "rate": 12 } },
    { "name": "Kenya", "currency": "Kenyan Shilling", "code": "KES", "symbol": "Sh", "tax": { "type": "VAT", "rate": 16 } },
    { "name": "Kiribati", "currency": "Australian Dollar", "code": "AUD", "symbol": "$", "tax": { "type": "None", "rate": 0 } },
    { "name": "North Korea", "currency": "North Korean Won", "code": "KPW", "symbol": "₩", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "South Korea", "currency": "South Korean Won", "code": "KRW", "symbol": "₩", "tax": { "type": "VAT", "rate": 10 } },
    { "name": "Kosovo", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Kuwait", "currency": "Kuwaiti Dinar", "code": "KWD", "symbol": "د.ك", "tax": { "type": "VAT", "rate": 5 } },
    { "name": "Kyrgyzstan", "currency": "Kyrgyzstani Som", "code": "KGS", "symbol": "лв", "tax": { "type": "VAT", "rate": 12 } },
    { "name": "Laos", "currency": "Lao Kip", "code": "LAK", "symbol": "₭", "tax": { "type": "VAT", "rate": 10 } },
    { "name": "Latvia", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 21 } },
    { "name": "Lebanon", "currency": "Lebanese Pound", "code": "LBP", "symbol": "ل.ل", "tax": { "type": "VAT", "rate": 11 } },
    { "name": "Lesotho", "currency": "Lesotho Loti", "code": "LSL", "symbol": "L", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Liberia", "currency": "Liberian Dollar", "code": "LRD", "symbol": "$", "tax": { "type": "GST", "rate": 10 } },
    { "name": "Libya", "currency": "Libyan Dinar", "code": "LYD", "symbol": "ل.د", "tax": { "type": "Sales", "rate": 4 } },
    { "name": "Liechtenstein", "currency": "Swiss Franc", "code": "CHF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 7.7 } },
    { "name": "Lithuania", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 21 } },
    { "name": "Luxembourg", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 17 } },
    { "name": "Madagascar", "currency": "Malagasy Ariary", "code": "MGA", "symbol": "Ar", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Malawi", "currency": "Malawian Kwacha", "code": "MWK", "symbol": "MK", "tax": { "type": "VAT", "rate": 16.5 } },
    { "name": "Malaysia", "currency": "Malaysian Ringgit", "code": "MYR", "symbol": "RM", "tax": { "type": "SST", "rate": 6 } },
    { "name": "Maldives", "currency": "Maldivian Rufiyaa", "code": "MVR", "symbol": "Rf", "tax": { "type": "GST", "rate": 6 } },
    { "name": "Mali", "currency": "West African CFA Franc", "code": "XOF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Malta", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Marshall Islands", "currency": "United States Dollar", "code": "USD", "symbol": "$", "tax": { "type": "Sales", "rate": 4 } },
    { "name": "Mauritania", "currency": "Mauritanian Ouguiya", "code": "MRU", "symbol": "UM", "tax": { "type": "VAT", "rate": 16 } },
    { "name": "Mauritius", "currency": "Mauritian Rupee", "code": "MUR", "symbol": "₨", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Mexico", "currency": "Mexican Peso", "code": "MXN", "symbol": "$", "tax": { "type": "VAT", "rate": 16 } },
    { "name": "Micronesia", "currency": "United States Dollar", "code": "USD", "symbol": "$", "tax": { "type": "Sales", "rate": 5 } },
    { "name": "Moldova", "currency": "Moldovan Leu", "code": "MDL", "symbol": "L", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Monaco", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Mongolia", "currency": "Mongolian Tögrög", "code": "MNT", "symbol": "₮", "tax": { "type": "VAT", "rate": 10 } },
    { "name": "Montenegro", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 21 } },
    { "name": "Morocco", "currency": "Moroccan Dirham", "code": "MAD", "symbol": "د.م.", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Mozambique", "currency": "Mozambican Metical", "code": "MZN", "symbol": "MT", "tax": { "type": "VAT", "rate": 17 } },
    { "name": "Myanmar", "currency": "Burmese Kyat", "code": "MMK", "symbol": "Ks", "tax": { "type": "Commercial", "rate": 5 } },
    { "name": "Namibia", "currency": "Namibian Dollar", "code": "NAD", "symbol": "$", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Nauru", "currency": "Australian Dollar", "code": "AUD", "symbol": "$", "tax": { "type": "None", "rate": 0 } },
    { "name": "Nepal", "currency": "Nepalese Rupee", "code": "NPR", "symbol": "₨", "tax": { "type": "VAT", "rate": 13 } },
    { "name": "Netherlands", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 21 } },
    { "name": "New Zealand", "currency": "New Zealand Dollar", "code": "NZD", "symbol": "$", "tax": { "type": "GST", "rate": 15 } },
    { "name": "Nicaragua", "currency": "Nicaraguan Córdoba", "code": "NIO", "symbol": "C$", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Niger", "currency": "West African CFA Franc", "code": "XOF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 19 } },
    { "name": "Nigeria", "currency": "Nigerian Naira", "code": "NGN", "symbol": "₦", "tax": { "type": "VAT", "rate": 7.5 } },
    { "name": "North Macedonia", "currency": "Macedonian Denar", "code": "MKD", "symbol": "ден", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Norway", "currency": "Norwegian Krone", "code": "NOK", "symbol": "kr", "tax": { "type": "VAT", "rate": 25 } },
    { "name": "Oman", "currency": "Omani Rial", "code": "OMR", "symbol": "ر.ع.", "tax": { "type": "VAT", "rate": 5 } },
    { "name": "Pakistan", "currency": "Pakistani Rupee", "code": "PKR", "symbol": "₨", "tax": { "type": "GST", "rate": 17 } },
    { "name": "Palau", "currency": "United States Dollar", "code": "USD", "symbol": "$", "tax": { "type": "PGST", "rate": 10 } },
    { "name": "Palestine", "currency": "Israeli New Shekel", "code": "ILS", "symbol": "₪", "tax": { "type": "VAT", "rate": 16 } },
    { "name": "Panama", "currency": "Panamanian Balboa", "code": "PAB", "symbol": "B/.", "tax": { "type": "ITBMS", "rate": 7 } },
    { "name": "Papua New Guinea", "currency": "Papua New Guinean Kina", "code": "PGK", "symbol": "K", "tax": { "type": "GST", "rate": 10 } },
    { "name": "Paraguay", "currency": "Paraguayan Guaraní", "code": "PYG", "symbol": "₲", "tax": { "type": "VAT", "rate": 10 } },
    { "name": "Peru", "currency": "Peruvian Sol", "code": "PEN", "symbol": "S/.", "tax": { "type": "IGV", "rate": 18 } },
    { "name": "Philippines", "currency": "Philippine Peso", "code": "PHP", "symbol": "₱", "tax": { "type": "VAT", "rate": 12 } },
    { "name": "Poland", "currency": "Polish Złoty", "code": "PLN", "symbol": "zł", "tax": { "type": "VAT", "rate": 23 } },
    { "name": "Portugal", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 23 } },
    { "name": "Qatar", "currency": "Qatari Riyal", "code": "QAR", "symbol": "ر.ق", "tax": { "type": "VAT", "rate": 5 } },
    { "name": "Romania", "currency": "Romanian Leu", "code": "RON", "symbol": "lei", "tax": { "type": "VAT", "rate": 19 } },
    { "name": "Russia", "currency": "Russian Ruble", "code": "RUB", "symbol": "₽", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Rwanda", "currency": "Rwandan Franc", "code": "RWF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Saint Kitts and Nevis", "currency": "East Caribbean Dollar", "code": "XCD", "symbol": "$", "tax": { "type": "VAT", "rate": 17 } },
    { "name": "Saint Lucia", "currency": "East Caribbean Dollar", "code": "XCD", "symbol": "$", "tax": { "type": "VAT", "rate": 12.5 } },
    { "name": "Saint Vincent and the Grenadines", "currency": "East Caribbean Dollar", "code": "XCD", "symbol": "$", "tax": { "type": "VAT", "rate": 16 } },
    { "name": "Samoa", "currency": "Samoan Tala", "code": "WST", "symbol": "T", "tax": { "type": "VAGST", "rate": 15 } },
    { "name": "San Marino", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 17 } },
    { "name": "São Tomé and Príncipe", "currency": "São Tomé and Príncipe Dobra", "code": "STN", "symbol": "Db", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Saudi Arabia", "currency": "Saudi Riyal", "code": "SAR", "symbol": "ر.س", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Senegal", "currency": "West African CFA Franc", "code": "XOF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Serbia", "currency": "Serbian Dinar", "code": "RSD", "symbol": "дин", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Seychelles", "currency": "Seychellois Rupee", "code": "SCR", "symbol": "₨", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Sierra Leone", "currency": "Sierra Leonean Leone", "code": "SLL", "symbol": "Le", "tax": { "type": "GST", "rate": 15 } },
    { "name": "Singapore", "currency": "Singapore Dollar", "code": "SGD", "symbol": "$", "tax": { "type": "GST", "rate": 8 } },
    { "name": "Slovakia", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Slovenia", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 22 } },
    { "name": "Solomon Islands", "currency": "Solomon Islands Dollar", "code": "SBD", "symbol": "$", "tax": { "type": "GST", "rate": 10 } },
    { "name": "Somalia", "currency": "Somali Shilling", "code": "SOS", "symbol": "Sh", "tax": { "type": "Sales", "rate": 5 } },
    { "name": "South Africa", "currency": "South African Rand", "code": "ZAR", "symbol": "R", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "South Sudan", "currency": "South Sudanese Pound", "code": "SSP", "symbol": "£", "tax": { "type": "Sales", "rate": 18 } },
    { "name": "Spain", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 21 } },
    { "name": "Sri Lanka", "currency": "Sri Lankan Rupee", "code": "LKR", "symbol": "Rs", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Sudan", "currency": "Sudanese Pound", "code": "SDG", "symbol": "£", "tax": { "type": "VAT", "rate": 17 } },
    { "name": "Suriname", "currency": "Surinamese Dollar", "code": "SRD", "symbol": "$", "tax": { "type": "Sales", "rate": 10 } },
    { "name": "Sweden", "currency": "Swedish Krona", "code": "SEK", "symbol": "kr", "tax": { "type": "VAT", "rate": 25 } },
    { "name": "Switzerland", "currency": "Swiss Franc", "code": "CHF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 7.7 } },
    { "name": "Syria", "currency": "Syrian Pound", "code": "SYP", "symbol": "£", "tax": { "type": "VAT", "rate": 10 } },
    { "name": "Taiwan", "currency": "New Taiwan Dollar", "code": "TWD", "symbol": "NT$", "tax": { "type": "VAT", "rate": 5 } },
    { "name": "Tajikistan", "currency": "Tajikistani Somoni", "code": "TJS", "symbol": "ЅМ", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Tanzania", "currency": "Tanzanian Shilling", "code": "TZS", "symbol": "Sh", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Thailand", "currency": "Thai Baht", "code": "THB", "symbol": "฿", "tax": { "type": "VAT", "rate": 7 } },
    { "name": "Timor-Leste", "currency": "United States Dollar", "code": "USD", "symbol": "$", "tax": { "type": "Sales", "rate": 2.5 } },
    { "name": "Togo", "currency": "West African CFA Franc", "code": "XOF", "symbol": "Fr", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Tonga", "currency": "Tongan Paʻanga", "code": "TOP", "symbol": "T$", "tax": { "type": "GST", "rate": 15 } },
    { "name": "Trinidad and Tobago", "currency": "Trinidad and Tobago Dollar", "code": "TTD", "symbol": "$", "tax": { "type": "VAT", "rate": 12.5 } },
    { "name": "Tunisia", "currency": "Tunisian Dinar", "code": "TND", "symbol": "د.ت", "tax": { "type": "VAT", "rate": 19 } },
    { "name": "Turkey", "currency": "Turkish Lira", "code": "TRY", "symbol": "₺", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "Turkmenistan", "currency": "Turkmenistani Manat", "code": "TMT", "symbol": "m", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Tuvalu", "currency": "Australian Dollar", "code": "AUD", "symbol": "$", "tax": { "type": "None", "rate": 0 } },
    { "name": "Uganda", "currency": "Ugandan Shilling", "code": "UGX", "symbol": "Sh", "tax": { "type": "VAT", "rate": 18 } },
    { "name": "Ukraine", "currency": "Ukrainian Hryvnia", "code": "UAH", "symbol": "₴", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "United Arab Emirates", "currency": "UAE Dirham", "code": "AED", "symbol": "د.إ", "tax": { "type": "VAT", "rate": 5 } },
    { "name": "United Kingdom", "currency": "British Pound Sterling", "code": "GBP", "symbol": "£", "tax": { "type": "VAT", "rate": 20 } },
    { "name": "United States", "currency": "United States Dollar", "code": "USD", "symbol": "$", "tax": { "type": "Sales", "rate": 0 } },
    { "name": "Uruguay", "currency": "Uruguayan Peso", "code": "UYU", "symbol": "$U", "tax": { "type": "VAT", "rate": 22 } },
    { "name": "Uzbekistan", "currency": "Uzbekistani Som", "code": "UZS", "symbol": "лв", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Vanuatu", "currency": "Vanuatu Vatu", "code": "VUV", "symbol": "VT", "tax": { "type": "VAT", "rate": 15 } },
    { "name": "Vatican City", "currency": "Euro", "code": "EUR", "symbol": "€", "tax": { "type": "VAT", "rate": 0 } },
    { "name": "Venezuela", "currency": "Venezuelan Bolívar", "code": "VES", "symbol": "Bs.S", "tax": { "type": "VAT", "rate": 16 } },
    { "name": "Vietnam", "currency": "Vietnamese Dong", "code": "VND", "symbol": "₫", "tax": { "type": "VAT", "rate": 10 } },
    { "name": "Yemen", "currency": "Yemeni Rial", "code": "YER", "symbol": "﷼", "tax": { "type": "GST", "rate": 5 } },
    { "name": "Zambia", "currency": "Zambian Kwacha", "code": "ZMW", "symbol": "ZK", "tax": { "type": "VAT", "rate": 16 } },
    { "name": "Zimbabwe", "currency": "Zimbabwean Dollar", "code": "ZWL", "symbol": "Z$", "tax": { "type": "VAT", "rate": 14.5 } }
  ];